### ISSUE TITLE
Failed prop type: Invalid prop `formComponents` of type `array` supplied to `FormWizard`, expected `object`.

### ISSUE THREAD

**Issue by colorwalf** [GlennChon/form-wizard#1]
index.js:2178 Warning: Failed prop type: Invalid prop `formComponents` of type `array` supplied to `FormWizard`, expected `object`.
    in FormWizard (at App.js:44)
    in App (at src/index.js:7)

seems like prop type check should be replaced ?
```
formComponents: PropTypes.array.isRequired
```
not
```
formComponents: PropTypes.object.isRequired
```

**Comment by SCD-24** [comment]
Fixed.  Thanks!
